### PR TITLE
Release 1.0.1

### PR DESCRIPTION
**Pull request by raovgarimella**

### CODE REVIEW

**Comment by hobywan** [comment]
It seems that you encountered the same errors as I had when releasing Wonton.
It was due to an incorrect removal of cinch submodule.
I fixed it with: 
```bash
git rm --cached cinch
git rm --cached wonton
git submodule update
git commit
git push origin release
```
Travis may still fail if the docker image does not contain the latest version of Wonton, since it is no longer a submodule.

**Review by hobywan — APPROVED** [review]
It seems that you encountered the same errors as I had when releasing Wonton.
It was due to an incorrect removal of cinch submodule.
I fixed it with: 
```bash
git rm --cached cinch
git rm --cached wonton
git submodule update
git commit
git push origin release
```
Travis may still fail if the docker image does not contain the latest version of Wonton, since it is no longer a submodule.

**Comment by raovgarimella** [comment]
I think you don't need the "git submodule update". I verified that .gitmodules is correctly updated in the repo with the original merge


---------------------------------------------------------
Rao V Garimella                 Tel: (505) 665-2928
T-5, MS B284                    Email: rao@lanl.gov
Los Alamos National Lab         '\    '\
Los Alamos, NM 87545              ( )-( )
---------------------------------------------------------

________________________________

**Comment by raovgarimella** [comment]
Travis CI fails because we need a Wonton docker image on DockerHub for building

**Comment by hobywan** [comment]
@raovgarimella 
I think you forgot to squash before merging.
There should be an option to do so:

squash

**Comment by raovgarimella** [comment]
Yes I did forget. I think Angela wanted us to squash the commits so that the internal history is not available.

Anything I can do to fix it now?


---------------------------------------------------------
Rao V Garimella                 Tel: (505) 665-2928
T-5, MS B284                    Email: rao@lanl.gov
Los Alamos National Lab         '\    '\
Los Alamos, NM 87545              ( )-( )
---------------------------------------------------------

________________________________

**Pull request merged**
